import os
import sys


def _asset(relative):
    if hasattr(sys, 'frozen'):
        base = sys._MEIPASS
    else:
        base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base, relative).replace('\\', '/')


_CHECK_SVG = _asset('assets/icon/check.svg')
_ARROW_UP_SVG = _asset('assets/icon/arrow_up.svg')
_ARROW_DOWN_SVG = _asset('assets/icon/arrow_down.svg')

_CHECKED_IMG = f'QCheckBox::indicator:checked {{ image: url({_CHECK_SVG}); }}\n'

_ARROWS_IMG = (
    f'QDoubleSpinBox::up-arrow   {{ image: url({_ARROW_UP_SVG}); }}\n'
    f'QDoubleSpinBox::down-arrow {{ image: url({_ARROW_DOWN_SVG}); }}\n'
    f'QComboBox::down-arrow      {{ image: url({_ARROW_DOWN_SVG}); width: 10px; height: 10px; }}\n'
)

_BASE = (
    '\n'
    '/* ── Buttons ─────────────────────────────────────────── */\n'
    'QPushButton {\n'
    '    background: #0984e3;\n'
    '    color: white;\n'
    '    border: none;\n'
    '    border-radius: 4px;\n'
    '    padding: 6px 18px;\n'
    '    font-size: 14px;\n'
    '    min-width: 72px;\n'
    '}\n'
    'QPushButton:hover   { background: #0773c9; }\n'
    'QPushButton:pressed { background: #0662b0; }\n'
    '\n'
    'QPushButton#stop_btn              { background: #d63031; color: white; min-width: 56px; max-width: 56px; padding: 6px 4px; font-weight: bold; }\n'
    'QPushButton#stop_btn:hover        { background: #b52828; }\n'
    'QPushButton#save_btn              { background: #00b894; color: white; font-weight: bold; font-size: 13px; padding: 4px 10px; min-width: 0; }\n'
    'QPushButton#save_btn:hover        { background: #00a381; }\n'
    'QPushButton#list_add_btn          { background: transparent; color: #0984e3; border: 1px solid #0984e3; padding: 2px 8px; font-size: 12px; min-width: 0; max-width: 80px; }\n'
    'QPushButton#list_add_btn:hover    { background: #0984e3; color: white; }\n'
    'QPushButton#list_del_btn          { background: transparent; color: #d63031; border: 1px solid #d63031; border-radius: 4px; font-size: 10px; padding: 0; min-width: 28px; max-width: 28px; min-height: 28px; max-height: 28px; }\n'
    'QPushButton#list_del_btn:hover    { background: #d63031; color: white; }\n'
    'QLabel#list_header_lbl            { color: #636e72; font-size: 13px; font-weight: bold; }\n'
    'QPushButton#start_btn             { background: #00b894; color: white; font-weight: bold; min-width: 56px; max-width: 56px; padding: 6px 4px; }\n'
    'QPushButton#start_btn:hover       { background: #00a381; }\n'
    '\n'
    '/* ── Tables ──────────────────────────────────────────── */\n'
    'QTableWidget::item     { padding: 4px 8px; }\n'
    'QHeaderView::section   {\n'
    '    border: none;\n'
    '    padding: 5px 8px;\n'
    '    font-weight: bold;\n'
    '    font-size: 13px;\n'
    '}\n'
    '\n'
    '/* ── Tabs ────────────────────────────────────────────── */\n'
    'QTabWidget::pane { border-radius: 6px; top: -1px; }\n'
    'QTabBar::tab {\n'
    '    border-bottom: none;\n'
    '    border-radius: 4px 4px 0 0;\n'
    '    padding: 6px 16px;\n'
    '    margin-right: 2px;\n'
    '    font-size: 13px;\n'
    '}\n'
    'QTabBar::tab:selected { font-weight: bold; }\n'
    '\n'
    '/* ── GroupBox ────────────────────────────────────────── */\n'
    'QGroupBox {\n'
    '    border-radius: 6px;\n'
    '    margin-top: 14px;\n'
    '    padding: 10px 10px 8px 10px;\n'
    '}\n'
    'QGroupBox::title {\n'
    '    subcontrol-origin: margin;\n'
    '    left: 10px;\n'
    '    padding: 0 6px;\n'
    '    font-size: 14px;\n'
    '    font-weight: bold;\n'
    '}\n'
    '\n'
    '/* ── Form controls ───────────────────────────────────── */\n'
    'QLineEdit, QDoubleSpinBox {\n'
    '    border-radius: 4px;\n'
    '    padding: 5px 8px;\n'
    '    min-height: 28px;\n'
    '}\n'
    'QLineEdit:focus, QDoubleSpinBox:focus { border-color: #4E4C97; }\n'
    'QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n'
    '    subcontrol-origin: border;\n'
    '    width: 24px;\n'
    '    border: none;\n'
    '}\n'
    'QDoubleSpinBox::up-button   { subcontrol-position: top right;    border-top-right-radius: 4px; }\n'
    'QDoubleSpinBox::down-button { subcontrol-position: bottom right; border-bottom-right-radius: 4px; }\n'
    'QDoubleSpinBox::up-arrow    { width: 8px; height: 8px; }\n'
    'QDoubleSpinBox::down-arrow  { width: 8px; height: 8px; }\n'
    '\n'
    'QComboBox {\n'
    '    border-radius: 4px;\n'
    '    padding: 5px 8px 5px 10px;\n'
    '    min-height: 28px;\n'
    '}\n'
    'QComboBox:focus { border-color: #4E4C97; }\n'
    'QComboBox::drop-down {\n'
    '    subcontrol-origin: border;\n'
    '    subcontrol-position: right center;\n'
    '    width: 24px;\n'
    '    border-left: 1px solid transparent;\n'
    '    border-top-right-radius: 4px;\n'
    '    border-bottom-right-radius: 4px;\n'
    '}\n'
    'QComboBox QAbstractItemView {\n'
    '    outline: none;\n'
    '    border-radius: 4px;\n'
    '    padding: 4px;\n'
    '}\n'
    'QComboBox QAbstractItemView::item {\n'
    '    padding: 6px 10px;\n'
    '    min-height: 26px;\n'
    '    border-radius: 3px;\n'
    '}\n'
    '\n'
    'QCheckBox { spacing: 6px; }\n'
    'QCheckBox::indicator {\n'
    '    width: 18px; height: 18px;\n'
    '    border-radius: 4px;\n'
    '}\n'
    'QCheckBox::indicator:checked {\n'
    '    background: #4E4C97;\n'
    '    border-color: #4E4C97;\n'
    '}\n'
    '\n'
    '/* ── ScrollBar ───────────────────────────────────────── */\n'
    'QScrollBar:vertical   { width: 8px; border-radius: 4px; margin: 0; }\n'
    'QScrollBar:horizontal { height: 8px; border-radius: 4px; }\n'
    'QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n'
    '    border-radius: 4px;\n'
    '}\n'
    'QScrollBar::handle:vertical   { min-height: 30px; }\n'
    'QScrollBar::handle:horizontal { min-width: 30px; }\n'
    'QScrollBar::add-line:vertical,  QScrollBar::sub-line:vertical  { height: 0; }\n'
    'QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal { width: 0; }\n'
    '\n'
    '/* ── Sidebar home button ─────────────────────────────── */\n'
    'QPushButton#sidebar_home_btn {\n'
    '    border: none;\n'
    '    border-radius: 0;\n'
    '    font-family: "Source Han Sans CN", "Noto Sans CJK SC", "Microsoft YaHei", sans-serif;\n'
    '    font-size: 14px;\n'
    '    text-align: left;\n'
    '    padding: 6px 0 6px 10px;\n'
    '}\n'
    '\n'
    '/* ── Account list ────────────────────────────────────── */\n'
    'QListWidget#account_list {\n'
    '    border: none;\n'
    '    outline: 0;\n'
    '    font-size: 14px;\n'
    '    padding: 0;\n'
    '}\n'
    'QListWidget#account_list::item {\n'
    '    padding: 6px 0 6px 10px;\n'
    '    border-bottom: 1px solid transparent;\n'
    '}\n'
    '\n'
    '/* ── Sidebar tree ────────────────────────────────────── */\n'
    'QTreeWidget {\n'
    '    border: none;\n'
    '    outline: 0;\n'
    '    font-size: 14px;\n'
    '}\n'
    'QTreeWidget::item { padding: 5px 4px 5px 2px; min-height: 24px; border-left: 3px solid transparent; outline: none; }\n'
    'QTreeWidget:focus { outline: none; }\n'
    'QTreeWidget::item:focus { outline: none; }\n'
    'QTreeWidget::branch:has-children { image: url(none); border-image: none; }\n'
    '\n'
    '/* ── Splitter handle ─────────────────────────────────── */\n'
    'QSplitter::handle:horizontal { width: 3px; }\n'
    '\n'
    '/* ── Custom title bar ────────────────────────────────── */\n'
    'QWidget#title_bar {\n'
    '    border-bottom: 1px solid transparent;\n'
    '}\n'
    'QLabel#title_icon {\n'
    '    border-radius: 4px;\n'
    '    background: transparent;\n'
    '}\n'
    'QLabel#title_bar_label {\n'
    '    font-size: 14px;\n'
    '    font-weight: bold;\n'
    '    background: transparent;\n'
    '}\n'
    'QLabel#title_bar_sep {\n'
    '    font-size: 14px;\n'
    '    background: transparent;\n'
    '}\n'
    'QLabel#title_bar_crumb {\n'
    '    font-size: 14px;\n'
    '    background: transparent;\n'
    '}\n'
    'QPushButton#wc_min, QPushButton#wc_max, QPushButton#wc_close {\n'
    '    background: transparent;\n'
    '    border: none;\n'
    '    border-radius: 0;\n'
    '    font-size: 20px;\n'
    '    font-weight: normal;\n'
    '    min-width: 38px;\n'
    '    max-width: 38px;\n'
    '    min-height: 38px;\n'
    '    max-height: 38px;\n'
    '    padding: 0;\n'
    '    color: #7c7c7c;\n'
    '}\n'
    '\n'
    '/* ── Log frame ───────────────────────────────────────── */\n'
    'QFrame#log_frame {\n'
    '    border-radius: 6px;\n'
    '}\n'
    '\n'
    '/* ── Sidebar handle toggle button ────────────────────── */\n'
    'QPushButton#sidebar_toggle_btn {\n'
    '    background: transparent;\n'
    '    border: none;\n'
    '    font-size: 14px;\n'
    '    min-width: 0;\n'
    '    padding: 0;\n'
    '}\n'
    '\n'
    '/* ── Theme toggle button (旧，保留兼容) ──────────────── */\n'
    'QPushButton#theme_toggle_btn {\n'
    '    background: #4E4C97;\n'
    '    color: white;\n'
    '    border: none;\n'
    '    border-radius: 4px;\n'
    '    padding: 4px 10px;\n'
    '    font-size: 13px;\n'
    '    font-weight: bold;\n'
    '    min-width: 0;\n'
    '}\n'
    '\n'
    '/* ── Theme segment buttons (暗色 / 亮色) ─────────────── */\n'
    'QPushButton#theme_seg_btn {\n'
    '    background: transparent;\n'
    '    border: 1px solid #4E4C97;\n'
    '    color: #4E4C97;\n'
    '    font-size: 13px;\n'
    '    padding: 4px 10px;\n'
    '    min-width: 0;\n'
    '    font-weight: normal;\n'
    '    border-radius: 4px;\n'
    '}\n'
    'QPushButton#theme_seg_btn:checked {\n'
    '    background: #4E4C97;\n'
    '    color: white;\n'
    '    font-weight: bold;\n'
    '}\n'
    'QPushButton#theme_seg_btn:hover:!checked { background: #eeedf8; }\n'
    '\n'
    '/* ── Home separator ──────────────────────────────────── */\n'
    'QFrame#home_sep { color: #dfe6e9; }\n'
    'QFrame#home_card { border: 1px solid #dfe6e9; border-radius: 8px; background: transparent; }\n'
    '\n'
    '/* ── Config row card ─────────────────────────────────── */\n'
    'QFrame#config_row {\n'
    '    border: 1px solid #e0e0e0;\n'
    '    border-radius: 6px;\n'
    '}\n'
    '\n'
    '/* ── Config management sort buttons ─────────────────── */\n'
    'QPushButton#config_sort_btn {\n'
    '    background: transparent;\n'
    '    color: #636e72;\n'
    '    border: 1px solid #b2bec3;\n'
    '    border-radius: 4px;\n'
    '    font-size: 13px;\n'
    '    padding: 3px 8px;\n'
    '    min-width: 0;\n'
    '}\n'
    'QPushButton#config_sort_btn:hover   { background: #dfe6e9; color: #2d3436; }\n'
    'QPushButton#config_sort_btn:pressed { background: #b2bec3; }\n'
    'QPushButton#config_sort_btn:disabled { color: #c0c0c0; border-color: #e0e0e0; }\n'
    '\n'
    '/* ── Config management rename button ─────────────────── */\n'
    'QPushButton#config_rename_btn {\n'
    '    background: #0984e3;\n'
    '    color: white;\n'
    '    border: none;\n'
    '    border-radius: 4px;\n'
    '    font-size: 13px;\n'
    '    padding: 5px 16px;\n'
    '    min-width: 0;\n'
    '}\n'
    'QPushButton#config_rename_btn:hover   { background: #0773c9; }\n'
    'QPushButton#config_rename_btn:pressed { background: #0662b0; }\n'
    '\n'
    '/* ── Multi-check toggle buttons ───────────────────────── */\n'
    'QPushButton#multi_check_btn {\n'
    '    background: transparent;\n'
    '    border: 1px solid #c4c3de;\n'
    '    border-radius: 4px;\n'
    '    font-size: 12px;\n'
    '    padding: 0;\n'
    '    min-width: 0;\n'
    '}\n'
    'QPushButton#multi_check_btn:hover:!checked { background: #eeedf8; }\n'
    'QPushButton#multi_check_btn:checked {\n'
    '    background: #4E4C97;\n'
    '    color: white;\n'
    '    border-color: #4E4C97;\n'
    '}\n'
    'QPushButton#multi_check_btn:checked:hover { background: #3d3b7a; }\n'
    '\n'
    '/* ── Config management delete button ─────────────────── */\n'
    'QPushButton#config_del_btn {\n'
    '    background: #d63031;\n'
    '    color: white;\n'
    '    border: none;\n'
    '    border-radius: 4px;\n'
    '    font-size: 13px;\n'
    '    padding: 5px 16px;\n'
    '    min-width: 0;\n'
    '}\n'
    'QPushButton#config_del_btn:hover   { background: #b52828; }\n'
    'QPushButton#config_del_btn:pressed { background: #9e2020; }\n'
    '\n'
    '/* ── Task row action buttons ─────────────────────────── */\n'
    'QPushButton#settings_shortcut_btn,\n'
    'QPushButton#action_close_btn,\n'
    'QPushButton#action_open_btn,\n'
    'QPushButton#action_reset_btn {\n'
    '    background: transparent;\n'
    '    border-radius: 2px;\n'
    '    font-size: 12px;\n'
    '    padding: 3px 8px;\n'
    '    min-width: 0;\n'
    '}\n'
    'QPushButton#settings_shortcut_btn { border: 1px solid #0984e3; color: #0984e3; }\n'
    'QPushButton#settings_shortcut_btn:hover { background: #e8f4fd; }\n'
    'QPushButton#action_close_btn { border: 1px solid #d63031; color: #d63031; }\n'
    'QPushButton#action_close_btn:hover { background: #fdecea; }\n'
    'QPushButton#action_open_btn  { border: 1px solid #00b894; color: #00b894; }\n'
    'QPushButton#action_open_btn:hover  { background: #e0faf4; }\n'
    'QPushButton#action_reset_btn { border: 1px solid #b2bec3; color: #2d3436; }\n'
    'QPushButton#action_reset_btn:hover { background: #f0f2f5; }\n'
    '\n'
    '/* ── Field description ───────────────────────────────── */\n'
    'QLabel#field_desc {\n'
    '    font-size: 12px;\n'
    '    line-height: 1.3;\n'
    '}\n'
    '\n'
    '/* ── Bool toggle button ──────────────────────────────── */\n'
    'QPushButton#bool_toggle_btn {\n'
    '    border-radius: 4px;\n'
    '    font-size: 13px;\n'
    '    font-weight: normal;\n'
    '    padding: 4px 10px;\n'
    '    min-width: 0;\n'
    '}\n'
    '\n'
    '/* ── Time error hint ─────────────────────────────────── */\n'
    'QLabel#time_error_lbl {\n'
    '    font-size: 11px;\n'
    '    color: #e74c3c;\n'
    '    padding: 0;\n'
    '}\n'
    '\n'
    '/* ── Toast ───────────────────────────────────────────── */\n'
    'QFrame#toast_label {\n'
    '    border-radius: 6px;\n'
    '    background: #00b894;\n'
    '}\n'
    '\n'
    '/* ── Reset config button ─────────────────────────────── */\n'
    'QPushButton#reset_config_btn {\n'
    '    background: transparent;\n'
    '    color: #95a5a6;\n'
    '    border: 1px solid #95a5a6;\n'
    '    border-radius: 4px;\n'
    '    padding: 2px 8px;\n'
    '    font-size: 12px;\n'
    '    font-weight: bold;\n'
    '    min-width: 0;\n'
    '}\n'
    'QPushButton#reset_config_btn:hover { background: #95a5a6; color: white; }\n'
    '\n'
    '/* ── Reset confirm dialog buttons ───────────────────── */\n'
    'QPushButton#reset_confirm_yes {\n'
    '    background: #e17055;\n'
    '    color: white;\n'
    '    border: none;\n'
    '    border-radius: 4px;\n'
    '    font-size: 13px;\n'
    '}\n'
    'QPushButton#reset_confirm_yes:hover { background: #c0392b; }\n'
    'QPushButton#reset_confirm_no {\n'
    '    background: transparent;\n'
    '    color: #636e72;\n'
    '    border: 1px solid #b2bec3;\n'
    '    border-radius: 4px;\n'
    '    font-size: 13px;\n'
    '}\n'
    'QPushButton#reset_confirm_no:hover { background: #f0f0f0; }\n'
    '\n'
    '/* ── Mode toggle button ──────────────────────────────── */\n'
    'QPushButton#mode_toggle_btn {\n'
    '    background: #eeecff;\n'
    '    color: #4E4C97;\n'
    '    border: 1px solid #4E4C97;\n'
    '    border-radius: 4px;\n'
    '    padding: 2px 10px;\n'
    '    font-size: 12px;\n'
    '    font-weight: bold;\n'
    '    min-width: 0;\n'
    '}\n'
    'QPushButton#mode_toggle_btn:hover { background: #4E4C97; color: white; }\n'
    '\n'
    '/* ── JSON editor ─────────────────────────────────────── */\n'
    'QTextEdit#json_editor {\n'
    '    border: 1px solid #c4c3de;\n'
    '    border-radius: 4px;\n'
    '    font-family: "Consolas", "Courier New", monospace;\n'
    '    font-size: 12px;\n'
    '    padding: 8px;\n'
    '}\n'
    '\n'
    '/* ── Task card frame ─────────────────────────────────── */\n'
    'QFrame#task_card {\n'
    '    border-radius: 6px;\n'
    '}\n'
    '\n'
    '/* ── Log header widget ───────────────────────────────── */\n'
    'QWidget#log_hdr {\n'
    '    background: transparent;\n'
    '}\n'
    '\n'
    '/* ── Log control buttons ─────────────────────────────── */\n'
    'QPushButton#log_ctrl_btn {\n'
    '    background: transparent;\n'
    '    border: 1px solid #b2bec3;\n'
    '    color: #636e72;\n'
    '    font-size: 12px;\n'
    '    padding: 2px 10px;\n'
    '    border-radius: 4px;\n'
    '    min-width: 0;\n'
    '}\n'
    'QPushButton#log_ctrl_btn:hover { color: #0984e3; border-color: #0984e3; }\n'
    'QPushButton#log_ctrl_btn:disabled { color: #c4c3de; border-color: #dfe6e9; }\n'
    '\n'
    '/* ── Log text ────────────────────────────────────────── */\n'
    'QTextEdit#log_text {\n'
    '    border: none;\n'
    '    border-radius: 0;\n'
    '    font-family: "Sarasa Mono SC", "Cascadia Mono", "Consolas", "Courier New", monospace;\n'
    '    font-size: 12px;\n'
    '}\n'
    '\n'
    '/* ── Tooltip ─────────────────────────────────────────── */\n'
    'QToolTip {\n'
    '    background: #2d3436;\n'
    '    color: #dfe6e9;\n'
    '    border: 1px solid #636e72;\n'
    '    padding: 4px 8px;\n'
    '    border-radius: 4px;\n'
    '    font-size: 13px;\n'
    '}\n'
    '\n'
    '/* ── Labels ──────────────────────────────────────────── */\n'
    'QLabel { background: transparent; }\n'
    '\n'
    '/* ── Section title ───────────────────────────────────── */\n'
    'QLabel#section_title {\n'
    '    font-size: 16px;\n'
    '    font-weight: bold;\n'
    '    padding: 4px 0;\n'
    '}\n'
    '\n'
    '/* ── Separator ───────────────────────────────────────── */\n'
    'QFrame[frameShape="4"], QFrame[frameShape="5"] { }\n'
)

_LIGHT_SUFFIX = (
    '\n'
    'QMainWindow, QWidget {\n'
    '    background: white;\n'
    '    font-family: "Source Han Sans CN", "Noto Sans CJK SC", "Microsoft YaHei", sans-serif;\n'
    '    font-size: 15px;\n'
    '    color: #2d3436;\n'
    '}\n'
    '\n'
    '/* Title bar */\n'
    'QWidget#title_bar { background: #ffffff; border-bottom: 1px solid #dfe6e9; }\n'
    'QLabel#title_bar_label { color: #2d3436; }\n'
    'QLabel#title_bar_sep { color: #b2bec3; }\n'
    'QLabel#title_bar_crumb { color: #4E4C97; font-weight: bold; }\n'
    'QPushButton#wc_min:hover, QPushButton#wc_max:hover { background: #e8ecf0; color: #2d3436; border-radius: 6px; }\n'
    'QPushButton#wc_close:hover { background: #e74c3c; color: white; border-radius: 6px; }\n'
    '\n'
    '/* Sidebar home button */\n'
    'QPushButton#sidebar_home_btn { background: #eaecf0; color: #2d3436; }\n'
    'QPushButton#sidebar_home_btn:hover { background: #eeedf8; color: #4E4C97; }\n'
    'QPushButton#sidebar_home_btn:checked {\n'
    '    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n'
    '        stop:0     #eeedf8,\n'
    '        stop:0.018 #eeedf8,\n'
    '        stop:0.019 #4E4C97,\n'
    '        stop:0.05  #4E4C97,\n'
    '        stop:0.051 #eeedf8,\n'
    '        stop:1     #eeedf8);\n'
    '    color: #4E4C97;\n'
    '}\n'
    '\n'
    '/* Account list */\n'
    'QListWidget#account_list {\n'
    '    background: #eaecf0;\n'
    '    color: #2d3436;\n'
    '}\n'
    'QListWidget#account_list::item {\n'
    '    border-bottom: 1px solid #dfe6e9;\n'
    '}\n'
    'QListWidget#account_list::item:hover {\n'
    '    background: #eeedf8;\n'
    '    color: #4E4C97;\n'
    '}\n'
    'QListWidget#account_list::item:selected {\n'
    '    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n'
    '        stop:0     #eeedf8,\n'
    '        stop:0.018 #eeedf8,\n'
    '        stop:0.019 #4E4C97,\n'
    '        stop:0.05  #4E4C97,\n'
    '        stop:0.051 #eeedf8,\n'
    '        stop:1     #eeedf8);\n'
    '    color: #4E4C97;\n'
    '    font-weight: bold;\n'
    '}\n'
    '\n'
    '/* Sidebar */\n'
    'QTreeWidget          { background: #f8f9fa; color: #2d3436; border-right: 1px solid #dfe6e9; }\n'
    'QTreeWidget::item:hover { background: #eeedf8; color: #4E4C97; }\n'
    'QTreeWidget::item:selected {\n'
    '    background: #f8f9fa;\n'
    '    color: #4E4C97;\n'
    '    border-left: 3px solid #4E4C97;\n'
    '}\n'
    'QTreeWidget::branch  { background: #f8f9fa; }\n'
    '\n'
    '/* Splitter */\n'
    'QSplitter::handle { background: transparent; }\n'
    'QFrame[frameShape="4"], QFrame[frameShape="5"] { color: #dfe6e9; }\n'
    '\n'
    '/* Panel drag handle */\n'
    'QWidget#panel_drag_handle { background: #dfe6e9; }\n'
    'QWidget#panel_drag_handle:hover { background: #b2bec3; }\n'
    '\n'
    '/* Panel expand button (restore collapsed left panel) */\n'
    'QPushButton#panel_expand_btn {\n'
    '    background: #eaecf0; color: #636e72;\n'
    '    border: none; border-right: 1px solid #dfe6e9;\n'
    '    border-radius: 0; font-size: 11px; padding: 0;\n'
    '}\n'
    'QPushButton#panel_expand_btn:hover { background: #eeedf8; color: #4E4C97; }\n'
    '\n'
    '/* Buttons */\n'
    'QPushButton:disabled { background: #b2bec3; color: #ecf0f1; }\n'
    '\n'
    '/* Tables */\n'
    'QTableWidget {\n'
    '    background: white; border: 1px solid #dfe6e9;\n'
    '    border-radius: 6px; gridline-color: #f5f6fa;\n'
    '    font-size: 12px; selection-background-color: #e8f4fd;\n'
    '    selection-color: #2d3436;\n'
    '}\n'
    'QHeaderView::section {\n'
    '    background: #f8f9fa;\n'
    '    border-bottom: 2px solid #dfe6e9;\n'
    '    color: #636e72;\n'
    '}\n'
    '\n'
    '/* Tabs */\n'
    'QTabWidget::pane { border: 1px solid #dfe6e9; background: white; }\n'
    'QTabBar::tab          { background: #ecf0f1; color: #636e72; border: 1px solid #dfe6e9; }\n'
    'QTabBar::tab:selected { background: white; color: #0984e3; border-color: #dfe6e9; }\n'
    'QTabBar::tab:hover:!selected { background: #dfe6e9; }\n'
    '\n'
    '/* GroupBox */\n'
    'QGroupBox { border: 1px solid #dfe6e9; background: white; }\n'
    'QGroupBox::title { color: #636e72; }\n'
    '\n'
    '/* Form */\n'
    'QLineEdit {\n'
    '    border: 1px solid #c4c3de; background: white; color: #2d3436;\n'
    '}\n'
    'QDoubleSpinBox {\n'
    '    border-top: 1px solid #c4c3de; border-left: 1px solid #c4c3de; border-bottom: 1px solid #c4c3de; border-right: none;\n'
    '    background: white; color: #2d3436;\n'
    '}\n'
    'QDoubleSpinBox::up-button { background: #f0f2f5; border-top: 1px solid #c4c3de; border-right: 1px solid #c4c3de; border-bottom: none; border-left: 1px solid #c4c3de; }\n'
    'QDoubleSpinBox::down-button { background: #f0f2f5; border-bottom: 1px solid #c4c3de; border-right: 1px solid #c4c3de; border-top: none; border-left: 1px solid #c4c3de; }\n'
    'QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover { background: #d0e8fb; }\n'
    'QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed { background: #0984e3; }\n'
    'QComboBox {\n'
    '    border-top: 1px solid #c4c3de; border-left: 1px solid #c4c3de; border-bottom: 1px solid #c4c3de; border-right: none;\n'
    '    background: white; color: #2d3436;\n'
    '}\n'
    'QComboBox::drop-down { border-top: 1px solid #c4c3de; border-right: 1px solid #c4c3de; border-bottom: 1px solid #c4c3de; border-left: 1px solid #c4c3de; background: #f8f9fa; }\n'
    'QComboBox::drop-down:hover { background: #eeedf8; }\n'
    'QComboBox QAbstractItemView {\n'
    '    background: white; border: 1px solid #c4c3de; color: #2d3436;\n'
    '}\n'
    'QComboBox QAbstractItemView::item:selected { background: #4E4C97; color: white; }\n'
    'QComboBox QAbstractItemView::item:hover:!selected { background: #eeedf8; color: #4E4C97; }\n'
    'QCheckBox::indicator { border: 1.5px solid #b2bec3; background: white; }\n'
    'QCheckBox::indicator:checked { border-color: #4E4C97; }\n'
    '\n'
    'QTextEdit {\n'
    '    border: 1px solid #c4c3de; border-radius: 4px;\n'
    '    background: white; color: #2d3436;\n'
    '}\n'
    'QListWidget {\n'
    '    border: 1px solid #c4c3de; border-radius: 4px;\n'
    '    background: white; color: #2d3436;\n'
    '}\n'
    'QListWidget::item { padding: 3px 6px; }\n'
    'QListWidget::item:selected { background: #0984e3; color: white; }\n'
    '\n'
    '/* ScrollBar */\n'
    'QScrollBar:vertical, QScrollBar:horizontal { background: #f5f6fa; }\n'
    'QScrollBar::handle:vertical, QScrollBar::handle:horizontal { background: #b2bec3; }\n'
    'QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover { background: #636e72; }\n'
    '\n'
    '/* Log */\n'
    'QTextEdit#log_text { background: white; }\n'
    'QFrame#log_frame { border: 1px solid #dfe6e9; background: white; }\n'
    'QFrame#log_hdr_sep { background: #dfe6e9; border: none; }\n'
    'QWidget#log_hdr  { background: transparent; }\n'
    '\n'
    '/* Task card */\n'
    'QFrame#task_card { background: white; border: 1px solid #dfe6e9; }\n'
    '/* Scheduler frame */\n'
    'QWidget#sched_frame { background: white; border: 1px solid #dfe6e9; border-radius: 6px; }\n'
    'QWidget#log_strip { background: white; }\n'
    '/* Misc */\n'
    'QPushButton#settings_shortcut_btn { color: #0984e3; }\n'
    'QPushButton#reset_config_btn { background: white; }\n'
    'QPushButton#sidebar_toggle_btn    { color: #95a5a6; }\n'
    'QPushButton#sidebar_toggle_btn:hover { color: #0984e3; }\n'
    'QPushButton#theme_toggle_btn { background: #4E4C97; color: white; font-weight: bold; border: none; }\n'
    'QPushButton#theme_toggle_btn:hover { background: #3d3b7a; color: white; }\n'
    'QFrame#config_row { background: white; }\n'
    'QFrame#config_row:hover { background: #fafafa; }\n'
    'QFrame#home_card { border-color: #dfe6e9; }\n'
    'QLabel#section_title { color: #2d3436; }\n'
    'QPushButton#bool_toggle_btn { background: #f0f2f5; color: #636e72; border: 1px solid #dfe6e9; }\n'
    'QPushButton#bool_toggle_btn:checked { background: #00b894; color: white; border-color: #00b894; }\n'
    'QPushButton#bool_toggle_btn:hover { background: #e8ecf0; }\n'
    'QPushButton#bool_toggle_btn:checked:hover { background: #00a381; }\n'
    'QFrame#toast_label { background: #00b894; }\n'
    'QLabel#field_desc { color: #636e72; }\n'
    'QTextEdit#json_editor { background: white; color: #2d3436; }\n'
    'QPushButton#mode_toggle_btn { background: #eeecff; color: #4E4C97; border-color: #4E4C97; }\n'
)

_DARK_SUFFIX = (
    '\n'
    'QMainWindow, QWidget {\n'
    '    background: #1e272e;\n'
    '    font-family: "Source Han Sans CN", "Noto Sans CJK SC", "Microsoft YaHei", sans-serif;\n'
    '    font-size: 15px;\n'
    '    color: #dfe6e9;\n'
    '}\n'
    'QLabel { background: transparent; }\n'
    'QCheckBox { background: transparent; }\n'
    '\n'
    '/* Title bar */\n'
    'QWidget#title_bar { background: #141d22; border-bottom: 1px solid #2d3436; }\n'
    'QLabel#title_bar_label { color: #dfe6e9; }\n'
    'QLabel#title_bar_sep { color: #636e72; }\n'
    'QLabel#title_bar_crumb { color: #9b99d4; font-weight: bold; }\n'
    'QPushButton#wc_min:hover, QPushButton#wc_max:hover { background: #2d3436; color: #b2bec3; border-radius: 6px; }\n'
    'QPushButton#wc_close:hover { background: #e74c3c; color: white; border-radius: 6px; }\n'
    '\n'
    '/* Sidebar home button */\n'
    'QPushButton#sidebar_home_btn { background: #141d22; color: #dfe6e9; }\n'
    'QPushButton#sidebar_home_btn:hover { background: #2a2840; color: #9b99d4; }\n'
    'QPushButton#sidebar_home_btn:checked {\n'
    '    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n'
    '        stop:0     #2a2840,\n'
    '        stop:0.018 #2a2840,\n'
    '        stop:0.019 #4E4C97,\n'
    '        stop:0.05  #4E4C97,\n'
    '        stop:0.051 #2a2840,\n'
    '        stop:1     #2a2840);\n'
    '    color: #9b99d4;\n'
    '}\n'
    '\n'
    '/* Account list */\n'
    'QListWidget#account_list {\n'
    '    background: #141d22;\n'
    '    color: #dfe6e9;\n'
    '}\n'
    'QListWidget#account_list::item {\n'
    '    border-bottom: 1px solid #2d3436;\n'
    '}\n'
    'QListWidget#account_list::item:hover {\n'
    '    background: #2a2840;\n'
    '    color: #9b99d4;\n'
    '}\n'
    'QListWidget#account_list::item:selected {\n'
    '    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n'
    '        stop:0     #2a2840,\n'
    '        stop:0.018 #2a2840,\n'
    '        stop:0.019 #4E4C97,\n'
    '        stop:0.05  #4E4C97,\n'
    '        stop:0.051 #2a2840,\n'
    '        stop:1     #2a2840);\n'
    '    color: #9b99d4;\n'
    '    font-weight: bold;\n'
    '}\n'
    '\n'
    '/* Sidebar */\n'
    'QTreeWidget          { background: #1a2327; color: #dfe6e9; }\n'
    'QTreeWidget::item:hover { background: #2a2840; color: #9b99d4; }\n'
    'QTreeWidget::item:selected {\n'
    '    background: #1a2327;\n'
    '    color: #9b99d4;\n'
    '    border-left: 3px solid #4E4C97;\n'
    '}\n'
    'QTreeWidget::branch  { background: #1a2327; }\n'
    '\n'
    '/* Splitter */\n'
    'QSplitter::handle { background: transparent; }\n'
    'QFrame[frameShape="4"], QFrame[frameShape="5"] { color: #2d3436; }\n'
    '\n'
    '/* Panel drag handle */\n'
    'QWidget#panel_drag_handle { background: #2d3436; }\n'
    'QWidget#panel_drag_handle:hover { background: #636e72; }\n'
    '\n'
    '/* Panel expand button */\n'
    'QPushButton#panel_expand_btn {\n'
    '    background: #141d22; color: #636e72; border: none;\n'
    '    border-right: 1px solid #2d3436; border-radius: 0;\n'
    '    font-size: 11px; padding: 0;\n'
    '}\n'
    'QPushButton#panel_expand_btn:hover { background: #2a2840; color: #9b99d4; }\n'
    '\n'
    '/* Buttons */\n'
    'QPushButton:disabled { background: #2d3436; color: #636e72; }\n'
    '\n'
    '/* Tables */\n'
    'QTableWidget {\n'
    '    background: #1b242a; border: 1px solid #2d3436;\n'
    '    border-radius: 6px; gridline-color: #253239;\n'
    '    font-size: 12px; selection-background-color: #2a2840;\n'
    '    selection-color: #dfe6e9;\n'
    '}\n'
    'QHeaderView::section {\n'
    '    background: #141d22;\n'
    '    border-bottom: 2px solid #2d3436;\n'
    '    color: #b2bec3;\n'
    '}\n'
    '\n'
    '/* Tabs */\n'
    'QTabWidget::pane { border: 1px solid #2d3436; background: #1e272e; }\n'
    'QTabBar::tab          { background: #141d22; color: #636e72; border: 1px solid #2d3436; }\n'
    'QTabBar::tab:selected { background: #1e272e; color: #0984e3; border-color: #2d3436; }\n'
    'QTabBar::tab:hover:!selected { background: #1b242a; }\n'
    '\n'
    '/* GroupBox */\n'
    'QGroupBox { border: 1px solid #2d3436; background: #1e272e; }\n'
    'QGroupBox::title { color: #b2bec3; }\n'
    '\n'
    '/* Form */\n'
    'QLineEdit {\n'
    '    border: 1px solid #2d3436; background: #141d22; color: #dfe6e9;\n'
    '}\n'
    'QDoubleSpinBox {\n'
    '    border-top: 1px solid #2d3436; border-left: 1px solid #2d3436; border-bottom: 1px solid #2d3436; border-right: none;\n'
    '    background: #141d22; color: #dfe6e9;\n'
    '}\n'
    'QDoubleSpinBox::up-button { background: #1b242a; border-top: 1px solid #2d3436; border-right: 1px solid #2d3436; border-bottom: none; border-left: 1px solid #2d3436; }\n'
    'QDoubleSpinBox::down-button { background: #1b242a; border-bottom: 1px solid #2d3436; border-right: 1px solid #2d3436; border-top: none; border-left: 1px solid #2d3436; }\n'
    'QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover { background: #2a2840; }\n'
    'QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed { background: #0984e3; }\n'
    'QComboBox {\n'
    '    border-top: 1px solid #2d3436; border-left: 1px solid #2d3436; border-bottom: 1px solid #2d3436; border-right: none;\n'
    '    background: #141d22; color: #dfe6e9;\n'
    '}\n'
    'QComboBox::drop-down { border-top: 1px solid #2d3436; border-right: 1px solid #2d3436; border-bottom: 1px solid #2d3436; border-left: 1px solid #2d3436; background: #1b242a; }\n'
    'QComboBox::drop-down:hover { background: #2a2840; }\n'
    'QComboBox QAbstractItemView {\n'
    '    background: #141d22; border: 1px solid #2d3436; color: #dfe6e9;\n'
    '}\n'
    'QComboBox QAbstractItemView::item:selected { background: #4E4C97; color: white; }\n'
    'QComboBox QAbstractItemView::item:hover:!selected { background: #2a2840; color: #9b99d4; }\n'
    'QCheckBox::indicator { border: 1.5px solid #636e72; background: #141d22; }\n'
    'QCheckBox::indicator:checked { border-color: #4E4C97; }\n'
    '\n'
    'QTextEdit {\n'
    '    border: 1px solid #2d3436; border-radius: 4px;\n'
    '    background: #141d22; color: #dfe6e9;\n'
    '}\n'
    'QListWidget {\n'
    '    border: 1px solid #2d3436; border-radius: 4px;\n'
    '    background: #141d22; color: #dfe6e9;\n'
    '}\n'
    'QListWidget::item { padding: 3px 6px; }\n'
    'QListWidget::item:selected { background: #0984e3; color: white; }\n'
    '\n'
    '/* ScrollBar */\n'
    'QScrollBar:vertical, QScrollBar:horizontal { background: #141d22; }\n'
    'QScrollBar::handle:vertical, QScrollBar::handle:horizontal { background: #2d3436; }\n'
    'QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover { background: #636e72; }\n'
    '\n'
    '/* Log */\n'
    'QTextEdit#log_text { background: #1e272e; }\n'
    'QFrame#log_frame { border: 1px solid #2d3436; background: #1e272e; }\n'
    'QFrame#log_hdr_sep { background: #2d3436; border: none; }\n'
    'QWidget#log_hdr  { background: transparent; }\n'
    '\n'
    '/* Task card */\n'
    'QFrame#task_card { background: #1e272e; border: 1px solid #2d3436; }\n'
    '/* Scheduler frame */\n'
    'QWidget#sched_frame { background: #1e272e; border: 1px solid #2d3436; border-radius: 6px; }\n'
    'QWidget#log_strip { background: #1e272e; }\n'
    '/* Misc */\n'
    'QPushButton#reset_config_btn { background: #141d22; }\n'
    'QPushButton#sidebar_toggle_btn    { color: #95a5a6; }\n'
    'QPushButton#sidebar_toggle_btn:hover { color: #0984e3; }\n'
    'QPushButton#theme_toggle_btn { background: #2a2840; color: #9b99d4; font-weight: bold; border: none; }\n'
    'QPushButton#theme_toggle_btn:hover { background: #4E4C97; color: white; }\n'
    'QFrame#config_row { background: #1e272e; }\n'
    'QFrame#config_row:hover { background: #141d22; }\n'
    'QFrame#home_card { border-color: #2d3436; }\n'
    'QLabel#section_title { color: #dfe6e9; }\n'
    'QPushButton#bool_toggle_btn { background: #141d22; color: #636e72; border: 1px solid #2d3436; }\n'
    'QPushButton#bool_toggle_btn:checked { background: #00b894; color: white; border-color: #00b894; }\n'
    'QPushButton#bool_toggle_btn:hover { background: #1b242a; }\n'
    'QPushButton#bool_toggle_btn:checked:hover { background: #00a381; }\n'
    'QFrame#toast_label { background: #00b894; }\n'
    'QLabel#field_desc { color: #b2bec3; }\n'
    'QTextEdit#json_editor { background: #141d22; color: #dfe6e9; }\n'
    'QPushButton#mode_toggle_btn { background: #1a1a30; color: #9b99d4; border-color: #4E4C97; }\n'
)

LIGHT_STYLE = _BASE + _LIGHT_SUFFIX + _CHECKED_IMG + _ARROWS_IMG
DARK_STYLE = _BASE + _DARK_SUFFIX + _CHECKED_IMG + _ARROWS_IMG
MAIN_STYLE = LIGHT_STYLE
